# config/opensearch-security/config.yml
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
    authc:
      basic_internal_auth_domain: 
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: internal
      jwt_auth_domain:
        description: "Authenticate via JWT"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: jwt
          challenge: false
          config:
            signing_key: "MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI="
            # algorithms: ["HS256"]
            jwt_header: "Authorization"
            jwt_url_parameter: token
            roles_key: roles
            subject_key: sub
            jwt_clock_skew_tolerance_seconds: 86400
        authentication_backend:
          type: noop