# config/opensearch-security/internal_users.yml
_meta:
  type: "internalusers"
  config_version: 2

admin:
  hash: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"  # password: admin
  reserved: false
  backend_roles:
    - "admin"
  description: "Admin user"

kibanaserver:
  hash: "$2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H."  # Set your password
  backend_roles:
    - "kibana_server"
    - "admin"