# config/opensearch-security/roles.yml
_meta:
  type: "roles"
  config_version: 2

admin_role:
  cluster_permissions:
    - "*"
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - "*"
  tenant_permissions:
    - tenant_patterns:
        - "*"
      allowed_actions:
        - "*"
  static: true

kibana_server_role:

  cluster_permissions:
    - "*"
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - "*"
  tenant_permissions:
    - tenant_patterns:
        - "*"
      allowed_actions:
        - "*"
  static: true 

# jwt_role:
#   cluster_permissions:
#     - "*"
#   index_permissions:
#     - index_patterns:
#         - "*"
#       allowed_actions:
#         - "*"
#   tenant_permissions:
#     - tenant_patterns:
#         - "*"
#       allowed_actions:
#         - "*"
#   static: true

jwt_user_role:
  cluster_permissions:
    - "*"
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - "*"
  tenant_permissions:
    - tenant_patterns:
        - "*"
      allowed_actions:
        - "*"
  static: true

jwt_admin_role:
  cluster_permissions:
    - "*"
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - "*"
  tenant_permissions:
    - tenant_patterns:
        - "*"
      allowed_actions:
        - "*"
  static: true