# Network and basic settings
network.host: 0.0.0.0
http.port: 9200
discovery.type: single-node

# Security plugin settings
plugins.security.disabled: false
plugins.security.allow_default_init_securityindex: true

# SSL/TLS configuration
plugins.security.ssl.transport.enabled: true
plugins.security.ssl.transport.pemcert_filepath: "/usr/share/opensearch/config/node.pem"
plugins.security.ssl.transport.pemkey_filepath: "/usr/share/opensearch/config/node-key.pem"
plugins.security.ssl.transport.pemtrustedcas_filepath: "/usr/share/opensearch/config/root-ca.pem"
plugins.security.ssl.transport.enforce_hostname_verification: false

plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.clientauth_mode: OPTIONAL
plugins.security.ssl.http.pemcert_filepath: "/usr/share/opensearch/config/node.pem"
plugins.security.ssl.http.pemkey_filepath: "/usr/share/opensearch/config/node-key.pem"
plugins.security.ssl.http.pemtrustedcas_filepath: "/usr/share/opensearch/config/root-ca.pem"

# Admin and Node DN Configuration
plugins.security.authcz.admin_dn:
  - "CN=admin,O=Org,L=City,ST=State,C=US"
plugins.security.nodes_dn:
  - "CN=node,O=Org,L=City,ST=State,C=US"

plugins.security.audit.type: internal_opensearch
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.check_snapshot_restore_write_privileges: true
# plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
plugins.security.restapi.roles_enabled: ["admin_role"]